version: '3.8'
services:
  db:
    container_name: book-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
  web:
    container_name: book-rails
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/bookapp
    ports:
      - "3000:3000"
  redis:
    container_name: book-redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - 8080:80
    volumes:
      - /sessions
